In [14]:
import numpy as np
A = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
B = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
C = np.tensordot(A, B , axes = ([2],[2]))
print(C)
print(A.shape)
print(B.shape)
print(C.shape)

[[[[14 32]
   [14 32]]

  [[32 77]
   [32 77]]]


 [[[14 32]
   [14 32]]

  [[32 77]
   [32 77]]]]
(2, 2, 3)
(2, 2, 3)
(2, 2, 2, 2)


In [1]:
for i in range(50):
    print("anhxinluibemo ;-;")

anhxinluibemo ;-;
anhxinluibemo ;-;
anhxinluibemo ;-;
anhxinluibemo ;-;
anhxinluibemo ;-;
anhxinluibemo ;-;
anhxinluibemo ;-;
anhxinluibemo ;-;
anhxinluibemo ;-;
anhxinluibemo ;-;
anhxinluibemo ;-;
anhxinluibemo ;-;
anhxinluibemo ;-;
anhxinluibemo ;-;
anhxinluibemo ;-;
anhxinluibemo ;-;
anhxinluibemo ;-;
anhxinluibemo ;-;
anhxinluibemo ;-;
anhxinluibemo ;-;
anhxinluibemo ;-;
anhxinluibemo ;-;
anhxinluibemo ;-;
anhxinluibemo ;-;
anhxinluibemo ;-;
anhxinluibemo ;-;
anhxinluibemo ;-;
anhxinluibemo ;-;
anhxinluibemo ;-;
anhxinluibemo ;-;
anhxinluibemo ;-;
anhxinluibemo ;-;
anhxinluibemo ;-;
anhxinluibemo ;-;
anhxinluibemo ;-;
anhxinluibemo ;-;
anhxinluibemo ;-;
anhxinluibemo ;-;
anhxinluibemo ;-;
anhxinluibemo ;-;
anhxinluibemo ;-;
anhxinluibemo ;-;
anhxinluibemo ;-;
anhxinluibemo ;-;
anhxinluibemo ;-;
anhxinluibemo ;-;
anhxinluibemo ;-;
anhxinluibemo ;-;
anhxinluibemo ;-;
anhxinluibemo ;-;
