In [3]:
import numpy as np 
A = np.random.rand(3,3)
B = np.random.rand(3,3)
print(A)
print(B)
C = A/B 
print(C)

[[0.63924124 0.42419447 0.24163499]
 [0.55068675 0.49410185 0.49379673]
 [0.4283553  0.25142778 0.8651299 ]]
[[0.99080348 0.22955687 0.74183123]
 [0.13211434 0.2845991  0.56878281]
 [0.94917233 0.15622864 0.59631434]]
[[0.6451746  1.84788406 0.32572771]
 [4.1682587  1.73613285 0.86816394]
 [0.45129349 1.6093578  1.45079506]]


In [4]:
import numpy as np 
A = np.random.rand(3,3)
print(A)
print(A+2)

[[2.59728696e-01 5.46204598e-01 7.75384687e-01]
 [7.61677832e-01 8.48432121e-01 5.78860112e-05]
 [8.20857832e-01 3.93818908e-01 8.78562085e-01]]
[[2.2597287  2.5462046  2.77538469]
 [2.76167783 2.84843212 2.00005789]
 [2.82085783 2.39381891 2.87856209]]
