In [3]:
import numpy as np

# Tạo hai tensor 3D ngẫu nhiên
A = np.random.rand(3, 4, 5)
B = np.random.rand(5, 5, 7)

print(A , "\n")
print(B)
# Nhân tensor A và B trên trục thứ 2 của A và trục thứ 0 của B
C = np.tensordot(A, B, axes=([2], [1]))
print("\n ================================= \n")
print(C.shape)  # Kết quả sẽ là (3, 4, 6, 7)
print(C)


[[[0.11131265 0.03328568 0.55788713 0.83934146 0.89659071]
  [0.80550344 0.9518103  0.39276697 0.71854188 0.40003882]
  [0.52382168 0.59899266 0.73724672 0.74225864 0.39978146]
  [0.77489777 0.03714268 0.81632262 0.50412504 0.32489499]]

 [[0.59547893 0.13871336 0.25826919 0.58211558 0.97648663]
  [0.06723354 0.50585003 0.62292789 0.5645403  0.9933704 ]
  [0.76848333 0.87421972 0.15294029 0.53713743 0.15519766]
  [0.61512555 0.50817615 0.26255175 0.40294267 0.99031594]]

 [[0.28118957 0.03419788 0.74941962 0.56258391 0.74523623]
  [0.45885738 0.68299871 0.17239571 0.1855222  0.11072267]
  [0.87969836 0.13538017 0.14163556 0.17608395 0.28371653]
  [0.39865337 0.46390359 0.15448632 0.67314722 0.15967628]]] 

[[[0.23218408 0.84067935 0.01277341 0.42405721 0.36970453 0.98381352
   0.0573804 ]
  [0.68377911 0.96746579 0.05738671 0.56750718 0.74861292 0.00678358
   0.0066366 ]
  [0.36095067 0.69093208 0.58597691 0.74046363 0.03001788 0.0673493
   0.76608746]
  [0.47787029 0.91089329 0.046753